# Generated by Django 6.0.3 on 2026-04-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_alter_job_posted_by_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
